AllCops:
  TargetRubyVersion: 2.1
  Include:
    - '**/Rakefile'
    - '**/Gemfile'

Style/DoubleNegation:
  Exclude:
    - 'lib/revolut/utils.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
