name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        ruby: [2.4, 2.5, 2.6, 2.7, '3.0']

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Test
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        bundle exec rspec

  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

        bundler-cache: true
    - name: RuboCop
      run: |
        bundle exec rubocop
